### ISSUE TITLE
Conduct! Empower the Crowd. Conduct!

### ISSUE THREAD

**Issue by rduplain** [cville/conduct#22]
Empower with one word: "Conduct!"

Misconduct happens, even with a clear code of conduct and great people in the community. To empower the crowd, I propose a rule in which anyone can say "Conduct!" when misconduct happens.

1. There's no way to prevent 100% of misconduct, and repair can only happen _after_. Provide a tool for anyone to interject in real time.
2. Sometimes people shout things in a crowd. Not everyone hears the shout-out, but those who do can respond.
3. Sometimes a session/room/subgroup does not have an organizer present (who knows the code of conduct in full and how to implement it). Make it simple.

By saying "Conduct!":

1. Unless the situation is very mild, do not give a reason. Just say "Conduct!" to interrupt the current flow.
2. If misconduct continues, repeat "Conduct!" Others can jump in and say it, too.
3. As a single word, there's no way to misinterpret the intent by saying "Conduct!", even if you don't know the code of conduct or that the event/group has a code of conduct. Conduct!
4. Organizers can jump in to unpack or the session can continue as planned, as appropriate to the situation.

**Comment by rduplain** [comment]
We want to be careful in shaming people, and to hold this in balance with the intent of the code of conduct.

**Comment by rduplain** [comment]
An idea behind this:

> Unless the situation is very mild, do not give a reason. Just say "Conduct!" to interrupt the current flow.

... is to empower without requiring you to then defend the _why_. As part of implementation of the code of conduct, there are organizers who are prepared to explain and defend _why_.

**Comment by philvarner** [comment]
Perhaps something less like shouting, and more like a polite, gentle reminder? "Conduct, please."

**Comment by rduplain** [comment]
Well, it doesn't have to be shouted. It could just be "Conduct." Feel free to add "please" to your taste. I'm opting for "less is more."

Allow me to provide to examples:

1. Someone shouts something lewd in the crowd.
2. Someone is presenting an article/paper/resource espousing superiority. It's clearly discrimination.

Possible responses, respectively:

1. You shout (less loudly), "Conduct!" This provides immediate feedback to the person that they are (or might be) crossing a line. It also stands in support of others who heard it and are surprised by the lewd comment. "Conduct!" is a tool to express zero tolerance in real time.
2. You want to apply the "Law of Two Feet" and leave, but you are concerned that by leaving, you are allowing discrimination to continue. (I have not tested this, but propose ...) You say "Conduct." as you otherwise quietly leave the room. For any number of reasons, you don't want to deal with this right now, and you opt out. But you opt out while flagging it for further review by the community.

More specifically in response to "Conduct, please." This is saying "Behave, if it pleases you." The code of conduct expects you to behave whether or not it pleases you. Saying "conduct" is a reference to the code of conduct, and to my knowledge, is not something that people would be used to hearing otherwise as a single-word interjection.

**Comment by rduplain** [comment]
To keep this balanced, we need a response to when people called you out with "Conduct!" when you were grossly misinterpreted (for which it's still reasonable to respond to what they perceived) or were wrongly accused.

**Comment by rduplain** [comment]
@sean-stockholm suggests that we include a way to say "Conduct." anonymously by texting/Slacking "Conduct." to an organizer. This is an excellent suggestion.

**Comment by rduplain** [comment]
Unpacking this further, if you feel frozen when misconduct happens (no matter how mild), you will not be able to exercise the tool that already exists: get in touch with an organizer.

(Also... Law of Two Feet is ablist.)

**Comment by andrew-boyd** [comment]
We could make a Slack command anyone could use in their self-chat channel that would message the admins with some follow-up information but also post to a given channel with an anonymous “someone has reported misconduct: [location] [summary]”

Bot could ask a series of questions to unpack the details.

**Comment by rduplain** [comment]
~You want to apply the "Law of Two Feet" ...~

You want to Vote with Your Attention ...

**Comment by rduplain** [comment]
Closing in favor of room captains:
[beCamp - room captain.pdf](https://github.com/cville/conduct/files/3666328/beCamp.-.room.captain.pdf)
