### ISSUE TITLE
Section about solicitation of free work

### ISSUE THREAD

**Issue by majtom2grndctrl** [cville/conduct#23]
Has there been any discussion over the years about a clause that covers solicitation of free work from event attendees and community members?

Is this possibly an example of something that could be covered by the “Repeated Invitations” section?

**Comment by Meekohi** [comment]
Sounds like repeated invitations could apply. This is like, someone
constantly asking for unpaid help on a project? Asking for volunteers?

**Comment by majtom2grndctrl** [comment]
Yeah, that is the general gist. I’m volunteering to help organize a meetup for designers, which is a cohort that attracts a fair amount of volume for that kind of request.

I just realized my initial question was unclear: I am not suggesting that the repeated invitations section be revised to include free work. My question is more along the lines of: When this kind of issue has come up in the past, has this section been a go-to for an answer to that problem?

**Comment by Meekohi** [comment]
I haven't seen this come up personally (at least to the point it was brought to my attention), would be curious if anyone else has! I would certainly try to address this with a frank conversation first and hope that would solve the issue in most cases, but if not, I do think the spirit of the "Repeating Invitations" section would apply.

**Comment by majtom2grndctrl** [comment]
I’ll follow-up with the people who raised the question in my group and get back to you. Thanks for your input!
