### ISSUE TITLE
Add Exception to the Prohibition on NSFW Topics

### ISSUE THREAD

**Issue by alexoxford** [cville/conduct#26]
The section [References to sexual or other not-suitable-for-work (NSFW) topics](https://github.com/cville/conduct#references-to-sexual-or-other-not-suitable-for-work-nsfw-topics) should have an exception for events/spaces where NSFW topics are explicitly allowed, and should list guidelines for how to ensure people are fully informed when entering such spaces

**Comment by Meekohi** [comment]
Closed in #27
