### ISSUE TITLE
empowerment

### ISSUE THREAD

**Issue by btaitelb** [cville/conduct#7]
Something that I feel isn't coming across in the current language of the CoC is that it isn't about listing all of the things that people _shouldn't_ do, but rather that it's here to empower our community to be a diverse, thriving scene. It empowers us in two main ways:
1. **filter** - by specifically delineating unacceptable behavior, we keep out a majority of people/behaviors that would make several of us uncomfortable
2. **tool** - by having an enforceable process to report and mitigate behavior that makes us feel unwelcome/uncomfortable, we feel empowered to come to safe spaces and discuss what we're passionate about. 

In practice, sometimes adult themes do come up (e.g. when discussing the dating apps and their UX), but being empowered by these tools means we can decide as a community what side of the line we're on.

---

Do you think it's worth it to make the language more empowering along these lines, or is that outside the scope of a CoC?

**Comment by Gorcenski** [comment]
Agree with the idea of making the CoC more empowering/proactive (i.e. what to do vs. what not to do). Could add language like, "encouraging diversity empowers the community" etc. etc. Would like to see more emphasis that diversity adds positive value vs. the notion that harassment adds negative value.
